general:
  debug: false
  instance_name: "Mi SearXNG"

server:
  secret_key: "reemplaza_con_texto_largo_aleatorio_aqui_123"
  public_instance: false

ui:
  default_locale: "es"
  default_theme: simple

search:
  safe_search: 1
  formats:
    - html
    - json

engines:
  - name: duckduckgo
    engine: duckduckgo
    shortcut: d
    disabled: false

  - name: wikipedia
    engine: wikipedia
    shortcut: w
    disabled: false