use_default_settings: true

server:
  secret_key: "reemplaza_con_texto_largo_aleatorio_aqui_123"
  bind_address: "0.0.0.0"
  port: 10000

search:
  formats:
    - html
    - json

use_default_settings:
  engines:
    keep_only:
      - duckduckgo
      - wikipedia